Group 1/Group 1/Group 1/MvcProject2/MvcProject2/Models/Cinema.cs
using MvcProject2.Models;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace MvcProject2.Models
{
    public class Cinema:IEntityBase
    {
        [Key]
        public int Id { get; set; }

        [Display(Name = "Cinema Logo")]
        [Required(ErrorMessage = "Cinema logo is required")]
        public string Logo { get; set; }

        [Display(Name = "Cinema Name")]
        [Required(ErrorMessage = "Cinema name is required")]
        public string Name { get; set; }

        [Display(Name = "Description")]
        [Required(ErrorMessage = "Cinema description is required")]
        public string Description { get; set; }

        //Relationships
        public List<Movie> Movies { get; set; }
    }
}

Group 1/Group 1/Group 1/MvcProject2/MvcProject2/Controllers/CinemasController.cs
using MvcProject2.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using MvcProject2.Repository;

namespace MvcProject2.Controllers
{
    [Authorize(Roles = UserRoles.Admin)]
    public class CinemasController : Controller
    {
        ICinemasReposatory cinemasReposatory;

        public CinemasController(ICinemasReposatory _cinemaRes)
        {
            cinemasReposatory = _cinemaRes;
        }

        [AllowAnonymous]
        public IActionResult Index()
        {
            var allCinemas = cinemasReposatory.GetAll();
            return View(allCinemas);
        }


        //Get: Cinemas/Create
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create([Bind("Name,Description")] Cinema cinema, IFormFile image)
        {
            //actor.ProfilePictureURL != null &
            if (cinema.Name != null & cinema.Description != null)
            {
                if (image != null && image.Length > 0)
                {
                    var fileName = Path.GetFileName(image.FileName);
                    var filePath = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot\\Images\\", fileName);

                    using (var fileStream = new FileStream(filePath, FileMode.Create))
                    {
                        image.CopyTo(fileStream);
                    }

                    cinema.Logo = "/Images/" + fileName;
                }

                cinemasReposatory.Insert(cinema);
                return RedirectToAction(nameof(Index));
            }
            return View(cinema);
        }

        //Get: Cinemas/Details/1
        [AllowAnonymous]
        public async Task<IActionResult> Details(int id)
        {
            var cinemaDetails = cinemasReposatory.GetByID(id);
            if (cinemaDetails == null) return View("NotFound");
            return View(cinemaDetails);
        }

        //Get: Cinemas/Edit/1
        public IActionResult Edit(int id)
        {
            var cinemaDetails = cinemasReposatory.GetByID(id);
            if (cinemaDetails == null) return View("NotFound");
            return View(cinemaDetails);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(int id, [Bind("Id,Name,Description")] Cinema cinema , IFormFile image)
        {

            if (cinema.Name != null & cinema.Description != null)
            {
                if (image != null && image.Length > 0)
                {
                    var fileName = Path.GetFileName(image.FileName);
                    var filePath = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot\\Images\\", fileName);

                    using (var fileStream = new FileStream(filePath, FileMode.Create))
                    {
                        image.CopyTo(fileStream);
                    }

                    cinema.Logo = "/Images/" + fileName;
                }

                cinemasReposatory.Edit(id, cinema);
                return RedirectToAction(nameof(Index));
            }
            return View(cinema);
        }


        //Get: Cinemas/Delete/1
        public IActionResult Delete(int id)
        {
            var cinemaDetails = cinemasReposatory.GetByID(id);
            if (cinemaDetails == null) return View("NotFound");
            return View(cinemaDetails);
        }

        [HttpPost, ActionName("Delete")]
        public IActionResult DeleteConfirm(int id)
        {
            var cinemaDetails = cinemasReposatory.GetByID(id);
            if (cinemaDetails == null) return View("NotFound");

            cinemasReposatory.Delete(id);
            return RedirectToAction(nameof(Index));
        }
    }
}

Group 1/Group 1/Group 1/MvcProject2/MvcProject2/Views/Cinemas/Create.cshtml
@using MvcProject2.Models;
@model Cinema

@{
    ViewData["Title"] = "Add a new cinema";
}
<head>
    <link rel="stylesheet"
          href="https://fonts.googleapis.com/css?family=Montserrat:wght@100;400;800&display=swap">
</head>
<style>
    body {
        background: url('../Images/body-bg.gif');
        background: black;
        color: white;
    }
</style>
<div class="row text">
    <div class="col-md-8 offset-2">
        <p>
            <h1>Add a New Cinema</h1>
        </p>
        <div class="row">
            <div class="col-md-8 offset-2">
  

                <div class="form-group">
                        <img id="preview" src="#" alt="Preview" style="display:none; max-width: 100%;" />
                    </div>
                

                <form asp-action="Create" asp-controller="Cinemas" method="post" enctype="multipart/form-data">
                    <div class="form-group">
                        <label asp-for="Name" class="control-label"></label>
                        <input asp-for="Name" class="form-control" />
                        <span asp-validation-for="Name" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label  class="control-label"> Cinema Logo</label>
                        
                       <input  type="file" name="image" id="image" class="form-control" />
                        
                        <span asp-validation-for="Logo" class="text-danger"></span>
                    </div>

                    
                    

                    <div class="form-group">
                        <label asp-for="Description" class="control-label"></label>
                        <textarea asp-for="Description" class="form-control"></textarea>
                        <span asp-validation-for="Description" class="text-danger"></span>
                    </div>
                    <button type="submit" class="btn btn-outline-success float-right">Create</button>
                    <a class="btn btn-outline-secondary" asp-action="Index">Show All</a>
                </form>

            </div>
        </div>
    </div>
</div>

@section Scripts{ 
    <script>

        $(document).ready(function () {
            var output = document.getElementById('CinemaLogoPreview');
            output.src = $("#Logo").val();
        })

        $("#Logo").on("change", function () {
            var output = document.getElementById('CinemaLogoPreview');
            output.src = $(this).val();
        })
    </script>
    <script>
    function readURL(input) {
        if (input.files && input.files[0]) {
            var reader = new FileReader();
            reader.onload = function(e) {
                document.getElementById('preview').src = e.target.result;
                document.getElementById('preview').style.display = 'block';
            }
            reader.readAsDataURL(input.files[0]); 
        }
    }
</script>
}

Group 1/Group 1/Group 1/MvcProject2/MvcProject2/Views/Cinemas/Delete.cshtml
@using MvcProject2.Models;
@model Cinema

@{
    ViewData["Title"] = "Delete cinema";
}

<head>
    <link rel="stylesheet"
          href="https://fonts.googleapis.com/css?family=Montserrat:wght@100;400;800&display=swap">
</head>
<style>
    body {
        background: url('../Images/body-bg.gif');
        background: black;
        color: white;
    }
</style>
<div class="row text">
    <div class="col-md-8 offset-2">
        <p>
            <h1>Delete confirmation for @Model.Name</h1>
        </p>
        <div class="row">
            <div class="col-md-8 offset-2">
                    <div class="form-group text-center">
                    <img class="border-info rounded-circle" style="width: 150px; height: 150px" id="LogoPreview" />
                    </div>
                    <div class="form-group">
                        <label asp-for="Logo" class="control-label"></label>
                        <input asp-for="Logo" class="form-control" readonly />
                        <span asp-validation-for="Logo" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Name" class="control-label"></label>
                        <input asp-for="Name" class="form-control" readonly />
                        <span asp-validation-for="Name" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Description" class="control-label"></label>
                        <input asp-for="Description" class="form-control" readonly />
                        <span asp-validation-for="Description" class="text-danger"></span>
                    </div>

                    <div class="form-group">
                        <form asp-action="Delete">
                            <input type="hidden" asp-for="Id" />
                            <input type="submit" value="Confirm" class="btn btn-danger float-right" />
                        </form>
                        <a class="btn btn-outline-secondary" asp-action="Index">Show All</a>
                    </div>
            </div>
        </div>
    </div>
</div>

@section Scripts{
    <script>
        $(document).ready(function () {
            var output = document.getElementById('LogoPreview');
            output.src = $("#Logo").val();
        })
    </script>
}

Group 1/Group 1/Group 1/MvcProject2/MvcProject2/Views/Cinemas/Details.cshtml
@using MvcProject2.Models;
@model Cinema

@{
    ViewData["Title"] = "Details of the cinema";
}

<head>
    <link rel="stylesheet"
          href="https://fonts.googleapis.com/css?family=Montserrat:wght@100;400;800&display=swap">
</head>
<style>
    body {
        background: url('../Images/body-bg.gif');
        background: black;
    }
</style>
<div class="row text">
    <div class="col-md-8 offset-2">
        <p>
            <h1>Details for @Model.Name</h1>
        </p>
        <div class="row">
            <div class="col-md-8 offset-2">
                    <div class="form-group text-center">
                    <img class="border-info rounded-circle" style="width: 150px; height: 150px" id="LogoPreview" />
                    </div>
                    <div class="form-group">
                        <label asp-for="Logo" class="control-label"></label>
                        <input asp-for="Logo" class="form-control" readonly />
                        <span asp-validation-for="Logo" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Name" class="control-label"></label>
                        <input asp-for="Name" class="form-control" readonly />
                        <span asp-validation-for="Name" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Description" class="control-label"></label>
                        <input asp-for="Description" class="form-control" readonly />
                        <span asp-validation-for="Description" class="text-danger"></span>
                    </div>

                    <div class="form-group">
                        @if (User.Identity.IsAuthenticated && User.IsInRole("Admin"))
                        {
                            <a class="btn btn-outline-success float-right" asp-action="Edit" asp-route-id="@Model.Id">Edit</a>
                        }
                            <a class="btn btn-outline-secondary" asp-action="Index">Show All</a>
                        </div>
            </div>
        </div>
    </div>
</div>

@section Scripts{
    <script>
        $(document).ready(function () {
            var output = document.getElementById('LogoPreview');
            output.src = $("#Logo").val();
        })
    </script>
}

Group 1/Group 1/Group 1/MvcProject2/MvcProject2/Views/Cinemas/Edit.cshtml
@using MvcProject2.Models;
@model Cinema

@{
    ViewData["Title"] = "Update cinema";
}
<head>
    <link rel="stylesheet"
          href="https://fonts.googleapis.com/css?family=Montserrat:wght@100;400;800&display=swap">
</head>
<style>
    body {
        background: url('../Images/body-bg.gif');
        background: black;
        color: white;
    }
</style>
<div class="row text">
    <div class="col-md-8 offset-2">
        <p>
            <h1>Update cinema</h1>
        </p>
        <div class="row">
            <div class="col-md-8 offset-2">
                
                    <div class="form-group text-center">
                        <img id="CinemaLogoPreview"  class="border-info rounded-circle" style="width: 150px; height:150px" />
                    </div>

                    <div class="form-group d-none">
                       <label asp-for="Logo" class="control-label"></label>
                        <input asp-for="Logo" class="form-control" />
                       <span asp-validation-for="Logo" class="text-danger"></span>
                    </div>
                
                <form asp-action="Edit" asp-controller="Cinemas" method="post" enctype="multipart/form-data">
                    <div class="form-group">
                        <label asp-for="Name" class="control-label"></label>
                        <input asp-for="Name" class="form-control" />
                        <span asp-validation-for="Name" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label Picture Image  class="control-label"> Cinema Logo</label>
                        <div class="custom-file">
                            <input asp-for="Logo"  type="file" name="image" id="image" class="form-control" />
                            <span asp-validation-for="Logo" class="text-danger"></span>
                        </div>
                     
                        
                    </div>
                    <div class="form-group">
                        <label asp-for="Description" class="control-label"></label>
                        <textarea asp-for="Description" class="form-control"></textarea>
                        <span asp-validation-for="Description" class="text-danger"></span>
                    </div>
                    <button type="submit" class="btn btn-outline-success float-right">Edit</button>
                    <a class="btn btn-outline-secondary" asp-action="Index">Show All</a>
                </form>


            </div>
        </div>
    </div>
</div>

@section Scripts{ 
    <script>

        $(document).ready(function () {
            var output = document.getElementById('CinemaLogoPreview');
            output.src = $("#Logo").val();
        })

        $("#Logo").on("change", function () {
            var output = document.getElementById('CinemaLogoPreview');
            output.src = $(this).val();
        })
    </script>
}

Group 1/Group 1/Group 1/MvcProject2/MvcProject2/Views/Cinemas/Index.cshtml
@using MvcProject2.Models;
@model IEnumerable<Cinema>

@{
    ViewData["Title"] = "List of Cinemas";
}
<head>
    <link rel="stylesheet"
          href="https://fonts.googleapis.com/css?family=Montserrat:wght@100;400;800&display=swap">
</head>
<style>
    body {
        background: url('../Images/body-bg.gif');
    }
</style>
<div class="row">
    <div class="col-md-8 offset-md-2">

        <table class="table table-dark table-hover">
            <thead>
                <tr class="text-center">
                    <th>@Html.DisplayNameFor(model => model.Logo)</th>
                    <th>@Html.DisplayNameFor(model => model.Name)</th>
                    <th>@Html.DisplayNameFor(model => model.Description)</th>
                    @if (User.Identity.IsAuthenticated && User.IsInRole("Admin"))
                    {
                        <th>Actions</th>
                    }
                    </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                <tr>
                    <td class="align-middle">
                            <img class="rounded-circle" src="@item.Logo" alt="@item.Name" style="width: 150px; height: 150px" />
                    </td>
                    <td class="align-middle">
                        @Html.DisplayFor(modelItem => item.Name)
                    </td>
                    <td class="align-middle">
                        @Html.DisplayFor(modelItem => item.Description)
                    </td>
                    @if (User.Identity.IsAuthenticated && User.IsInRole("Admin"))
                    {
                        <td class="align-middle">
                            <a class="btn btn-outline-primary" asp-action="Edit" asp-route-id="@item.Id"><i class="bi bi-pencil-square"></i>Edit </a> |
                            <a class="btn btn-outline-info" asp-action="Details" asp-route-id="@item.Id"><i class="bi bi-eye"></i>Details </a> |
                            <a class="btn btn-danger text-white" asp-action="Delete" asp-route-id="@item.Id"><i class="bi bi-trash"></i>Delete </a>
                        </td>
                    }
                    </tr>
                }
            </tbody>

        </table>

    </div>
</div>

@await Html.PartialAsync("_CreateItem", "Cinemas") 