Group 1/Group 1/Group 1/MvcProject2/MvcProject2/Models/Producer.cs
using MvcProject2.Models;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace MvcProject2.Models
{
    public class Producer:IEntityBase
    {
        [Key]
        public int Id { get; set; }

        [Display(Name = "Profile Picture")]
        [Required(ErrorMessage = "Profile Picture is required")]
        public string ProfilePictureURL { get; set; }

        [Display(Name = "Full Name")]
        [Required(ErrorMessage = "Full Name is required")]
        [StringLength(50, MinimumLength = 3, ErrorMessage = "Full Name must be between 3 and 50 chars")]
        public string FullName { get; set; }

        [Display(Name = "Biography")]
        [Required(ErrorMessage = "Biography is required")]
        public string Bio { get; set; }

        //Relationships
        public List<Movie> Movies { get; set; }
    }
}

Group 1/Group 1/Group 1/MvcProject2/MvcProject2/Controllers/ProducersController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using MvcProject2.Models;
using MvcProject2.Repository;

namespace MvcProject2.Controllers
{
    [Authorize(Roles = UserRoles.Admin)]
    public class ProducersController : Controller
    {
        private readonly IProducersRepository producersRepository;

        public ProducersController(IProducersRepository producersRepository)
        {
           this. producersRepository = producersRepository;
        }

        [AllowAnonymous]
        public async Task<IActionResult> Index()
        {
            var allProducers = await producersRepository.GetAllAsync();
            return View(allProducers);
        }

        //GET: producers/details/1
        [AllowAnonymous]
        public async Task<IActionResult> Details(int id)
        {
            var producerDetails = await producersRepository.GetByIdAsync(id);
            if (producerDetails == null) return View("NotFound");
            return View(producerDetails);
        }

        //GET: producers/create
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create([Bind("FullName,Bio")] Producer p ,IFormFile image)
        {
            //actor.ProfilePictureURL != null &
            if (p.FullName != null & p.Bio != null)
            {
                if (image != null && image.Length > 0)
                {
                    var fileName = Path.GetFileName(image.FileName);
                    var filePath = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot\\Images\\", fileName);

                    using (var fileStream = new FileStream(filePath, FileMode.Create))
                    {
                        image.CopyTo(fileStream);
                    }

                  p.ProfilePictureURL = "/Images/" + fileName;
                }

                producersRepository.Add(p);
                return RedirectToAction(nameof(Index));
            }
            return View(p);
        }


        //GET: producers/edit/1
        public async Task<IActionResult> Edit(int id)
        {
            var producerDetails = await producersRepository.GetByIdAsync(id);
            if (producerDetails == null) return View("NotFound");
            return View(producerDetails);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]

        public  IActionResult Edit(int id, [Bind("Id,FullName,Bio")] Producer p, IFormFile image)
        {

            if (p.FullName != null & p.Bio != null)
            {
                if (image != null && image.Length > 0)
                {
                    var fileName = Path.GetFileName(image.FileName);
                    var filePath = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot\\Images\\", fileName);

                    using (var fileStream = new FileStream(filePath, FileMode.Create))
                    {
                        image.CopyTo(fileStream);
                    }

                  p.ProfilePictureURL = "/Images/" + fileName;
                }

                producersRepository.Update(id, p);
                return RedirectToAction(nameof(Index));
            }
            return View(p);
        }

        //GET: producers/delete/1
        public async Task<IActionResult> Delete(int id)
        {
            var producerDetails = await producersRepository.GetByIdAsync(id);
            if (producerDetails == null) return View("NotFound");
            return View(producerDetails);
        }

        [HttpPost, ActionName("Delete")]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var producerDetails = await producersRepository.GetByIdAsync(id);
            if (producerDetails == null) return View("NotFound");

             producersRepository.Delete(id);
            return RedirectToAction(nameof(Index));
        }
    }
}

Group 1/Group 1/Group 1/MvcProject2/MvcProject2/Views/Producers/Create.cshtml
@using MvcProject2.Models;
@model Producer

@{
    ViewData["Title"] = "Add a new producer";
}
<head>
    <link rel="stylesheet"
          href="https://fonts.googleapis.com/css?family=Montserrat:wght@100;400;800&display=swap">
</head>
<style>
    body {
        background: url('../Images/body-bg.gif');
        background: black;
        color: white;
    }
</style>
<div class="row text">
    <div class="col-md-8 offset-2">
        <p>
            <h1>Add a New Producer</h1>
        </p>
        <div class="row">
            <div class="col-md-8 offset-2">
                
                    <div class="form-group text-center">
                        <img id="ProfilePicturePreview" class="border-info rounded-circle" style="max-width: 150px" />
                    </div>
                
                <form asp-action="Create" asp-controller="Producers" method="post" enctype="multipart/form-data">
                    <div class="form-group">
                        <label asp-for="FullName" class="control-label"></label>
                        <input asp-for="FullName" class="form-control" />
                        <span asp-validation-for="FullName" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                            <label   class="control-label">Picture Image</label>
                        <div class="custom-file">
                            <input  type="file" name="image" id="image" class="form-control" />
                            <span asp-validation-for="ProfilePictureURL" class="text-danger"></span>
                    
                        </div>
                    </div>
                    <div class="form-group">
                        <label asp-for="Bio" class="control-label"></label>
                        <textarea asp-for="Bio" class="form-control"></textarea>
                        <span asp-validation-for="Bio" class="text-danger"></span>
                    </div>
                    <button type="submit" class="btn btn-outline-success float-right">Create</button>
                    <a class="btn btn-outline-secondary" asp-action="Index">Show All</a>
                </form>


            </div>
        </div>
    </div>
</div>

Group 1/Group 1/Group 1/MvcProject2/MvcProject2/Views/Producers/Delete.cshtml
@using MvcProject2.Models;
@model Producer

@{
    ViewData["Title"] = "Delete producer";
}
<head>
    <link rel="stylesheet"
          href="https://fonts.googleapis.com/css?family=Montserrat:wght@100;400;800&display=swap">
</head>
<style>
    body {
        background: url('../Images/body-bg.gif');
        background: black;
        color: white;
    }
</style>
<div class="row text">
    <div class="col-md-8 offset-2">
        <p>
            <h1>Delete confirmation for @Model.FullName</h1>
        </p>
        <div class="row">
            <div class="col-md-8 offset-2">
                    <div class="form-group text-center">
                    <img class="border-info rounded-circle" style="width: 150px; height: 150px" id="ProfilePicturePreview" />
                    </div>
                    <div class="form-group">
                        <label asp-for="ProfilePictureURL" class="control-label"></label>
                        <input asp-for="ProfilePictureURL" class="form-control" readonly />
                        <span asp-validation-for="ProfilePictureURL" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="FullName" class="control-label"></label>
                        <input asp-for="FullName" class="form-control" readonly />
                        <span asp-validation-for="FullName" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Bio" class="control-label"></label>
                        <input asp-for="Bio" class="form-control" readonly />
                        <span asp-validation-for="Bio" class="text-danger"></span>
                    </div>

                    <div class="form-group">
                        <form asp-action="Delete">
                            <input type="hidden" asp-for="Id" />
                            <input type="submit" value="Confirm" class="btn btn-danger float-right" />
                        </form>
                        <a class="btn btn-outline-secondary" asp-action="Index">Show All</a>
                    </div>
            </div>
        </div>
    </div>
</div>

@section Scripts{
    <script>
        $(document).ready(function () {
            var output = document.getElementById('ProfilePicturePreview');
            output.src = $("#ProfilePictureURL").val();
        })
    </script>
}

Group 1/Group 1/Group 1/MvcProject2/MvcProject2/Views/Producers/Details.cshtml
@using MvcProject2.Models;
@model Producer

@{
    ViewData["Title"] = "Details of the producer";
}

<head>
    <link rel="stylesheet"
          href="https://fonts.googleapis.com/css?family=Montserrat:wght@100;400;800&display=swap">
</head>
<style>
    body {
        background: url('../Images/body-bg.gif');
        background: black;
        color: white;
    }
</style>
<div class="row text">
    <div class="col-md-8 offset-2">
        <p>
            <h1>Details for @Model.FullName</h1>
        </p>
        <div class="row">
            <div class="col-md-8 offset-2">
                <div class="form-group text-center">
                    <img class="border-info rounded-circle" style="width: 150px; height: 150px" id="ProfilePicturePreview" />
                </div>
                <div class="form-group">
                    <label asp-for="ProfilePictureURL" class="control-label"></label>
                    <input asp-for="ProfilePictureURL" class="form-control" readonly />
                    <span asp-validation-for="ProfilePictureURL" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="FullName" class="control-label"></label>
                    <input asp-for="FullName" class="form-control" readonly />
                    <span asp-validation-for="FullName" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Bio" class="control-label"></label>
                    <input asp-for="Bio" class="form-control" readonly />
                    <span asp-validation-for="Bio" class="text-danger"></span>
                </div>

                <div class="form-group">
                    @if (User.Identity.IsAuthenticated && User.IsInRole("Admin"))
                    {
                        <a class="btn btn-outline-success float-right" asp-action="Edit" asp-route-id="@Model.Id">Edit</a>
                    }
                        <a class="btn btn-outline-secondary" asp-action="Index">Show All</a>
                    </div>
            </div>
        </div>
    </div>
</div>

@section Scripts{
    <script>
        $(document).ready(function () {
            var output = document.getElementById('ProfilePicturePreview');
            output.src = $("#ProfilePictureURL").val();
        })
    </script>
}

Group 1/Group 1/Group 1/MvcProject2/MvcProject2/Views/Producers/Edit.cshtml
@using MvcProject2.Models;
@model Producer

@{
    ViewData["Title"] = "Update producer";
}
<head>
    <link rel="stylesheet"
          href="https://fonts.googleapis.com/css?family=Montserrat:wght@100;400;800&display=swap">
</head>
<style>
    body {
        background: url('../Images/body-bg.gif');
        background: black;
        color: white;
    }
</style>
<div class="row text">
    <div class="col-md-8 offset-2">
        <p>
            <h1>Update Producer</h1>
        </p>
        <div class="row">
            <div class="col-md-8 offset-2">
                
                    <div class="form-group text-center">
                        <img id="ProfilePicturePreview"  class="border-info rounded-circle" style="width: 150px;height:150px" />
                    </div>

                     <div class="form-group d-none">
                        <label asp-for="ProfilePictureURL" class="control-label"></label>
                        <input asp-for="ProfilePictureURL" class="form-control" />
                        <span asp-validation-for="ProfilePictureURL" class="text-danger"></span>
                    </div>
                
                <form asp-action="Edit" asp-controller="Producers" method="post" enctype="multipart/form-data">
                    <div class="form-group">
                        <label asp-for="FullName" class="control-label"></label>
                        <input asp-for="FullName" class="form-control" />
                        <span asp-validation-for="FullName" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label   class="control-label">Picture Image</label>
                        <div class="custom-file">
                            <input  type="file" name="image" id="image" class="form-control" />
                        </div>
                        <span asp-validation-for="ProfilePictureURL" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Bio" class="control-label"></label>
                        <textarea asp-for="Bio" class="form-control"></textarea>
                        <span asp-validation-for="Bio" class="text-danger"></span>
                    </div>
                   <div class="form-group">
                        <input type="submit" value="Update" class="btn btn-outline-success float-right" />
                        <a class="btn btn-outline-secondary" asp-action="Index">Show All</a>
                    </div>  
                    
                </form>

            </div>
        </div>
    </div>
</div>

@section Scripts{ 
    <script>

        $(document).ready(function () {
            var output = document.getElementById('ProfilePicturePreview');
            output.src = $("#ProfilePictureURL").val();
        })

        $("#ProfilePictureURL").on("change", function () {
            var output = document.getElementById('ProfilePicturePreview');
            output.src = $(this).val();
        })
    </script>
}

Group 1/Group 1/Group 1/MvcProject2/MvcProject2/Views/Producers/Index.cshtml
@using MvcProject2.Models;
@model IEnumerable<Producer>

@{
    ViewData["Title"] = "List of Producers";
}

<head>
    <link rel="stylesheet"
          href="https://fonts.googleapis.com/css?family=Montserrat:wght@100;400;800&display=swap">
</head>
<style>
    body {
        background: url('../Images/body-bg.gif');
    }
</style>
<div class="row">
    <div class="col-md-8 offset-md-2">

        <table table class="table table-dark table-hover">
            <thead>
                <tr class="text-center">
                    <th>@Html.DisplayNameFor(model => model.ProfilePictureURL)</th>
                    <th>@Html.DisplayNameFor(model => model.FullName)</th>
                    <th>@Html.DisplayNameFor(model => model.Bio)</th>
                    @if (User.Identity.IsAuthenticated && User.IsInRole("Admin"))
                    {
                        <th>Actions</th>
                    }
                    </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                <tr>
                    <td class="align-middle">
                        <img class="rounded-circle" src="@item.ProfilePictureURL" alt="@item.FullName" style="width: 150px; height: 150px" />
                    </td>
                    <td class="align-middle">
                        @Html.DisplayFor(modelItem => item.FullName)
                    </td>
                    <td class="align-middle">
                        @Html.DisplayFor(modelItem => item.Bio)
                    </td>
                    @if (User.Identity.IsAuthenticated && User.IsInRole("Admin"))
                    {
                        <td class="align-middle">
                            <a class="btn btn-outline-primary" asp-action="Edit" asp-route-id="@item.Id"><i class="bi bi-pencil-square"></i>Edit </a> |
                            <a class="btn btn-outline-info" asp-action="Details" asp-route-id="@item.Id"><i class="bi bi-eye"></i>Details </a> |
                            <a class="btn btn-danger text-white" asp-action="Delete" asp-route-id="@item.Id"><i class="bi bi-trash"></i>Delete </a>
                        </td>
                    }
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>

@await Html.PartialAsync("_CreateItem", "Producers") 