Group 1/Group 1/Group 1/MvcProject2/MvcProject2/Controllers/ActorsController.cs
//using .Data;
//using eTickets.Data.Static;
using MvcProject2.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using MvcProject2.Repository;

namespace MvcProject2.Controllers
{
    [Authorize(Roles = UserRoles.Admin)]
    public class ActorsController : Controller
    {
        IActorReposatory actorReposatory;   

        public ActorsController(IActorReposatory _actorRes)
        {
            actorReposatory = _actorRes;

        }

        [AllowAnonymous]
        public IActionResult Index()
        {
            var allActors = actorReposatory.GetAll();
            return View(allActors);
        }

        //Get: Actors/Create\
        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create([Bind("FullName,Bio")] Actor actor, IFormFile image)
        {
            //actor.ProfilePictureURL != null &
            if (actor.FullName != null & actor.Bio != null )
            {
                if (image != null && image.Length > 0)
                {
                    var fileName = Path.GetFileName(image.FileName);
                    var filePath = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot\\Images\\", fileName);

                    using (var fileStream = new FileStream(filePath, FileMode.Create))
                    {
                        image.CopyTo(fileStream);
                    }

                    actor.ProfilePictureURL = "/Images/" + fileName;
                }

                actorReposatory.Insert(actor);
                return RedirectToAction(nameof(Index));
            }
            return View(actor);
        }




        //Get: Actors/Details/1
        [AllowAnonymous]
        public IActionResult Details(int id)
        {
            var actorDetails = actorReposatory.GetByID(id);

            if (actorDetails == null) return View("NotFound");
            return View(actorDetails);
        }

        //Get: Actors/Edit/1
        [HttpGet]
        public IActionResult Edit(int id)
        {
            var actorDetails = actorReposatory.GetByID(id);
            if (actorDetails == null) return View("NotFound");
            return View(actorDetails);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(int id, [Bind("Id,FullName,Bio")] Actor actor, IFormFile image)
        {
            if (actor.FullName != null & actor.Bio != null)
            {
                if (image != null && image.Length > 0)
                {
                    var fileName = Path.GetFileName(image.FileName);
                    var filePath = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot\\Images\\", fileName);

                    using (var fileStream = new FileStream(filePath, FileMode.Create))
                    {
                        image.CopyTo(fileStream);
                    }

                    actor.ProfilePictureURL = "/Images/" + fileName;
                }

                actorReposatory.Edit(id, actor);
                return RedirectToAction(nameof(Index));
            }
            return View(actor);
        }





        //Get: Actors/Delete/1
        public IActionResult Delete(int id)
        {
            var actorDetails = actorReposatory.GetByID(id);
            if (actorDetails == null) return View("NotFound");
            return View(actorDetails);
        }

        [HttpPost, ActionName("Delete")]
        public IActionResult DeleteConfirmed(int id)
        {
            var actorDetails = actorReposatory.GetByID(id);
            if (actorDetails == null) return View("NotFound");

            actorReposatory.Delete(id);
            return RedirectToAction(nameof(Index));
        }
    }
}

Group 1/Group 1/Group 1/MvcProject2/MvcProject2/Controllers/MoviesController.cs
using MvcProject2.ViewModels;
using MvcProject2.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using MvcProject2.Repository;

namespace MvcProject2.Controllers
{
    [Authorize(Roles = UserRoles.Admin)]
    public class MoviesController : Controller
    {
        IMovieRepository moviesRepository;

        public MoviesController(IMovieRepository _movieRepo)
        {
            moviesRepository = _movieRepo;
        }

        [AllowAnonymous]
        public IActionResult Index()
        {
            var allMovies = moviesRepository.GetAllAsync();
            return View(allMovies);
        }

        [AllowAnonymous]
        public IActionResult Filter(string searchString)
        {
            var allMovies = moviesRepository.GetAllAsync();

            if (!string.IsNullOrEmpty(searchString))
            {
                var filteredResultNew = allMovies.Where(n => string.Equals(n.Name, searchString, System.StringComparison.CurrentCultureIgnoreCase) || string.Equals(n.Description, searchString, System.StringComparison.CurrentCultureIgnoreCase)).ToList();

                return View("Index", filteredResultNew);
            }

            return View("Index", allMovies);
        }

        [AllowAnonymous]
        public async Task<IActionResult> Details(int id)
        {
            var movieDetail = await moviesRepository.GetMovieById(id);
       
            return View(movieDetail);
        }

        public IActionResult Create()
        {
            var movieDropdownsData = moviesRepository.GetNewMovieDropdownsValues();

            ViewBag.Cinemas = new SelectList(movieDropdownsData.Cinemas, "Id", "Name");
            ViewBag.Producers = new SelectList(movieDropdownsData.Producers, "Id", "FullName");
            ViewBag.Actors = new SelectList(movieDropdownsData.Actors, "Id", "FullName");
            var enumData = from MovieCategory e in Enum.GetValues(typeof(MovieCategory))
                           select new
                           {
                               Id = (int)e,
                               FullName = e.ToString()
                           };
            ViewBag.Categories = new SelectList(enumData, "Id", "FullName");

            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(NewMovieVM movie, IFormFile image)
        {
            movie.ImageURL = "/Images/pexels - alex - azabache - 3879071.jpg";
            if (movie.Name != null && movie.Description != null && movie.Price != null
                 && movie.StartDate != null && movie.EndDate != null && movie.MovieCategory != null
                 && movie.ActorIds != null && movie.ActorIds.Count > 0 && movie.CinemaId != null
                 && movie.ProducerId != null)
            {
                if (image != null && image.Length > 0)
                {
                    var fileName = Path.GetFileName(image.FileName);
                    var filePath = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot\\Images\\", fileName);

                    using (var fileStream = new FileStream(filePath, FileMode.Create))
                    {
                        image.CopyTo(fileStream);
                    }

                    movie.ImageURL = "/Images/" + fileName;
                }

               await moviesRepository.AddNewMovieAsync(movie);
                return RedirectToAction("Index");
            }
            else
            {
                var movieDropdownsData = moviesRepository.GetNewMovieDropdownsValues();

                ViewBag.Cinemas = new SelectList(movieDropdownsData.Cinemas, "Id", "Name");
                ViewBag.Producers = new SelectList(movieDropdownsData.Producers, "Id", "FullName");
                ViewBag.Actors = new SelectList(movieDropdownsData.Actors, "Id", "FullName");
                var enumData = from MovieCategory e in Enum.GetValues(typeof(MovieCategory))
                               select new
                               {
                                   Id = (int)e,
                                   FullName = e.ToString()
                               };
                ViewBag.Categories = new SelectList(enumData, "Id", "FullName");

                return View(movie);
            }
        }


        public async Task<ActionResult> Edit(int id)
        {
            var movieDetails = await moviesRepository.GetMovieById(id);
            if (movieDetails == null) return View("NotFound");

            var response = new NewMovieVM()
            {
                Id = movieDetails.Id,
                Name = movieDetails.Name,
                Description = movieDetails.Description,
                Price = movieDetails.Price,
                StartDate = movieDetails.StartDate,
                EndDate = movieDetails.EndDate,
                ImageURL = movieDetails.ImageURL,
                MovieCategory = movieDetails.MovieCategory,
                CinemaId = movieDetails.CinemaId,
                ProducerId = (int)movieDetails.ProducerId,
                ActorIds = movieDetails.Actors_Movies.Select(n => n.ActorId).ToList(),
            };

            var movieDropdownsData = moviesRepository.GetNewMovieDropdownsValues();
            ViewBag.Cinemas = new SelectList(movieDropdownsData.Cinemas, "Id", "Name");
            ViewBag.Producers = new SelectList(movieDropdownsData.Producers, "Id", "FullName");
            ViewBag.Actors = new SelectList(movieDropdownsData.Actors, "Id", "FullName");
            var enumData = from MovieCategory e in Enum.GetValues(typeof(MovieCategory))
                           select new
                           {
                               Id = (int)e,
                               FullName = e.ToString()
                           };
            ViewBag.Categories = new SelectList(enumData, "Id", "FullName");

            return View(response);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, NewMovieVM movie, IFormFile image)
        {
            if (id != movie.Id) return View("NotFound");

            if (movie.Name != null && movie.Description != null && movie.Price != null
                && movie.StartDate != null && movie.EndDate != null && movie.MovieCategory != null
                && movie.ActorIds != null && movie.ActorIds.Count > 0 && movie.CinemaId != null
                && movie.ProducerId != null)
            {

                if (image != null && image.Length > 0)
                {
                    var fileName = Path.GetFileName(image.FileName);
                    var filePath = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot\\Images\\", fileName);

                    using (var fileStream = new FileStream(filePath, FileMode.Create))
                    {
                        image.CopyTo(fileStream);
                    }

                    movie.ImageURL = "/Images/" + fileName;

                    await moviesRepository.UpdateMovieAsync(movie);

                    return RedirectToAction("Index");
                }
                await moviesRepository.UpdateMovieAsync(movie);

                return RedirectToAction("Index");
                //return View(movie);

            }
            var movieDropdownsData = moviesRepository.GetNewMovieDropdownsValues();

            ViewBag.Cinemas = new SelectList(movieDropdownsData.Cinemas, "Id", "Name");
            ViewBag.Producers = new SelectList(movieDropdownsData.Producers, "Id", "FullName");
            ViewBag.Actors = new SelectList(movieDropdownsData.Actors, "Id", "FullName");
            var enumData = from MovieCategory e in Enum.GetValues(typeof(MovieCategory))
                           select new
                           {
                               Id = (int)e,
                               FullName = e.ToString()
                           };
            ViewBag.Categories = new SelectList(enumData, "Id", "FullName");

            return View(movie);


        }
        public IActionResult Delete(int id)
        {
            moviesRepository.DeleteMovie(id);
            return RedirectToAction("Index");
        }

    }
}

Group 1/Group 1/Group 1/MvcProject2/MvcProject2/Views/Movies/Create.cshtml
@using MvcProject2.ViewModels;
@model NewMovieVM

@{
    ViewData["Title"] = "Create a new movie";
}
<head>
    <link rel="stylesheet"
          href="https://fonts.googleapis.com/css?family=Montserrat:wght@100;400;800&display=swap">
</head>
<style>
    body {
        background: url('../Images/body-bg.gif');
        background: black;
        color: white;
    }
</style>
<div class="row">
    <div class="col-md-8 offset-2">
        <p>
            <h4>Create a new movie</h4>
        </p>

        <div class="row">
            <div class="col-md-8 offset-2">
                <form asp-action="Create" asp-controller="Movies" method="post" enctype="multipart/form-data">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>

                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group">
                                <label asp-for="Name" class="control-label"></label>
                                <input asp-for="Name" class="form-control" />
                                <span asp-validation-for="Name" class="text-danger"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for="StartDate" class="control-label"></label>
                                <input asp-for="StartDate" type="date" class="form-control" />
                                <span asp-validation-for="StartDate" class="text-danger"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for="EndDate" class="control-label"></label>
                                <input asp-for="EndDate" type="date" class="form-control" />
                                <span asp-validation-for="EndDate" class="text-danger"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for="Price" class="control-label"></label>
                                <input asp-for="Price" type="number" class="form-control" />
                                <span asp-validation-for="Price" class="text-danger"></span>
                            </div>
                            <div class="form-group">
                                <label class="control-label">Picture Image</label>
                                <div class="custom-file">
                                    <input type="file" name="image" id="image" class="form-control" />
                                </div>
                                <span asp-validation-for="ImageURL" class="text-danger"></span>
                            </div>

                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                <label asp-for="CinemaId" class="control-label"></label>
                                <select asp-for="CinemaId" class="form-control" asp-items="ViewBag.Cinemas"></select>
                                <span asp-validation-for="CinemaId" class="text-danger"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for="MovieCategory" class="control-label"></label>
                                <select asp-for="MovieCategory" class="form-control" asp-items="Html.GetEnumSelectList<MovieCategory>()"></select>
                                <span asp-validation-for="MovieCategory" class="text-danger"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for="ProducerId" class="control-label"></label>
                                <select asp-for="ProducerId" class="form-control" asp-items="ViewBag.Producers"></select>
                                <span asp-validation-for="ProducerId" class="text-danger"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for="ActorIds" class="control-label"></label>
                                <select asp-for="ActorIds" class="form-control" asp-items="ViewBag.Actors" multiple></select>
                                <span asp-validation-for="ActorIds" class="text-danger"></span>
                            </div>
                        </div>
                        <div class="col-md-12">
                            <div class="form-group">
                                <label asp-for="Description" class="control-label"></label>
                                <textarea asp-for="Description" class="form-control"></textarea>
                                <span asp-validation-for="Description" class="text-danger"></span>
                            </div>
                        </div>
                         </div>

                    <div class="col-md-4 offset-4 text-center">
                        <img width="100%" id="ImageUrlPreview" />
                    </div>

                    <div class="form-group">
                        <input type="submit" value="Create" class="btn btn-outline-success float-right" />
                        <a class="btn btn-outline-secondary" asp-action="Index">Show all</a>
                    </div>

                </form>
                
            </div>
        </div>

    </div>
</div>

@section Scripts{
    <script>
        $("#ImageURL").on("change", function () {
            var output = document.getElementById("ImageUrlPreview");
            output.src = $(this).val();
        })
    </script>
}

Group 1/Group 1/Group 1/MvcProject2/MvcProject2/Views/Movies/Details.cshtml
@using MvcProject2.Models;
@model Movie

@{
    ViewData["Title"] = "Movie details";
}
<head>
    <link rel="stylesheet"
          href="https://fonts.googleapis.com/css2?family=Roboto:wght@300&display=swap">
</head>
<style>
    * {
        margin: 0;
        padding: 0;
        box-sizing: border-box;
    }

     body {

        background: url('../Images/body-bg.gif');
        background:black;
        color:black;
        font-family: "Roboto", sans-serif;
      
    }

    .movie {
        max-width: 800px;
        border-radius: 5px;
        display: flex;
        box-shadow: 0 5px 20px 10px rgba(0, 0, 0, .2);
        overflow: hidden;
        margin-left: 346px;
    }

    .movie__hero {
        flex: 0 0 45%;
    }

    .movie__img {
        width: 100%;
        height: 100%;
        display: block;
    }

    .movie__content {
        background-color: aliceblue;
        flex: 1;
        padding: 35px 30px;
        display: flex;
        flex-direction: column;
    }

    .movie__price {
        background: linear-gradient(to bottom, #A9C9FF 0%, #FFBBEC 100%);
        flex: 0 0 50px;
        font-size: 18px;
        font-weight: bold;
        letter-spacing: 2px;
        color: rgb(255, 255, 255);
        writing-mode: vertical-lr;
        display: flex;
        align-items: center;
        justify-content: center;
    }

    .movie__title {
        display: flex;
        align-items: center;
        margin-bottom: 20px;
    }

    .heading__primary {
        font-size: 16px;
        margin-right: auto;
        color: royalblue;
    }

    .fa-fire {
        color: salmon;
    }

    .movie__tag {
        font-size: 10px;
        color: #fff;
        padding: 2px 7px;
        border-radius: 100px;
        margin-right: 8px;
        display: block;
        text-transform: uppercase;
    }

    .movie__tag--1 {
        background-color: #FFBBEC;
    }

    .movie__tag--2 {
        background-color: #FFBBEC;
    }

    .movie__description {
        font-size: 14px;
    }

    .movie__details {
        display: flex;
        margin: auto;
    }

    .movie__detail {
        font-size: 13px;
        margin-right: 20px;
        display: flex;
        align-items: center;
    }

    .mar {
        margin-top: 30px;
    }

    .icons i {
        margin-right: 3px;
        font-size: 18px;
    }

    .icons-red {
        color: salmon;
    }

    .icons-grey {
        color: grey;
    }

    .icons-yellow {
        color: rgb(190, 190, 71);
    }
</style>
<figure class="movie">
    <div class="movie__hero">
        <img src="@Model.ImageURL" alt="Rambo" class="movie__img">
    </div>
    <div class="movie__content">
        <div class="movie__title">
            <h1 class="heading__primary"> @Model.Name<i class="fas fa-fire"></i></h1>
            <div class="movie__tag movie__tag--1">@Model.MovieCategory</div>
            <p class="card-text ">

                @if (DateTime.Now >= Model.StartDate && DateTime.Now <= Model.EndDate)
                {
                    <span class="badge bg-success text-white">AVAILABLE</span>
                }
                else if (DateTime.Now > Model.EndDate)
                {
                    <span class="badge bg-danger text-white">EXPIRED</span>
                }
                else
                {
                    <span class="badge bg-primary text-white">UPCOMING</span>
                }
            </p>
        </div>
        <p class="movie__description">
            @Model.Description
        </p>
        <div class="movie__details">
            <p class="movie__detail">
                 @if (User.Identity.IsAuthenticated && User.IsInRole("Admin"))
                                    {
										<a asp-action="Delete"  asp-route-id="@Model.Id"  formnovalidate class="Cancel" onclick="
                                            return confirm('Are you sure you want to delete this movie?')"> <i class="fa-solid fa-trash-can"></i></a>
                                    }
            </p>
            <p class="movie__detail"><span class="icons icons-grey"><i class="fas fa-clock"></i><b>Start Date: </b> @Model.StartDate.ToString("dd MMM yy")</span></p>
            <p class="movie__detail"><span class="icons icons-grey"><i class="fas fa-clock"></i><b>End Date: </b> @Model.EndDate.ToString("dd MMM yy")</span></p>
            <p class="movie__detail"></p>

        </div>


        <div class="movie__details">
            <div class="row">

                <div class="row">

                    <b>Actors: </b>

                </div>
                <div class="row">
                    @foreach (var actor in Model.Actors_Movies)
                    {
                        <div class="col">

                            <br />
                            <a asp-controller="Actors" asp-action="Details" asp-route-id="@actor.ActorId"> <img class="border-info rounded-circle" src="@actor.Actor.ProfilePictureURL" style="width: 70px; height:70px" /></a>
                        </div>
                    }
                </div>

            </div>
        </div>

        <div class="movie__details">
            <div class="row">

                <div class="row">
                    <div class="col">
                        <b> Producer</b>
                    </div>
                    <div class="col">
                        <b>Cinema: </b>
                    </div>


                </div>
                <div class="row">
                    <div class="col">
                        <a asp-controller="Producers" asp-action="Details" asp-route-id="@Model.ProducerId">
                            <img class="border-info rounded-circle" src="@Model.Producer.ProfilePictureURL" style="width: 70px; height:70px" />
                        </a>

                    </div>

                    <div class="col">
                        <a asp-controller="Cinemas" asp-action="Details" asp-route-id="@Model.CinemaId">
                            <img class="border-info rounded-circle" src="@Model.Cinema.Logo" style="max-width: 70px" />
                        </a>

                    </div>

                </div>

            </div>
        </div>




        <div class="row mar">


            <div class="col">
                <a class="btn btn-outline-primary  btn-md  p-2.9 " asp-action="Index">
                    <svg xmlns="http://www.w3.org/2000/svg" width="18" height="18" fill="currentColor" class="bi bi-arrow-left-circle-fill" viewBox="0 0 16 16">
                        <path d="M8 0a8 8 0 1 0 0 16A8 8 0 0 0 8 0zm3.5 7.5a.5.5 0 0 1 0 1H5.707l2.147 2.146a.5.5 0 0 1-.708.708l-3-3a.5.5 0 0 1 0-.708l3-3a.5.5 0 1 1 .708.708L5.707 7.5H11.5z" />
                    </svg>
                    Back to List
                </a>

            </div>
            <div class="col">
                <a class="btn btn-success btn-md  p-2.9 text-white  @((DateTime.Now > Model.EndDate) ? "disabled" : "")"
                   asp-controller="Orders"
                   asp-action="AddItemToShoppingCart" asp-route-id="@Model.Id"><i class="bi bi-cart-plus"></i> Add to Cart </a>

            </div>

        </div>


       

    </div>
    <div class="movie__price"> @Model.Price.ToString("c")</div>


</figure>

Group 1/Group 1/Group 1/MvcProject2/MvcProject2/Views/Movies/Edit.cshtml
@model MvcProject2.ViewModels.NewMovieVM

@{
    ViewData["Title"] = "Edit";
}
<head>
    <link rel="stylesheet"
          href="https://fonts.googleapis.com/css?family=Montserrat:wght@100;400;800&display=swap">
</head>
<style>
    body {
        background: url('../Images/body-bg.gif');
        background: black;
        color: white;
    }
</style>
<h1>Edit</h1>

<h4>Movie</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit" asp-controller="Movies" method="post" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Price" class="control-label"></label>
                <input asp-for="Price" class="form-control" />
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>
            <div class="form-group">
                                <label class="control-label">Picture Image</label>
                                <div class="custom-file">
                                    <input type="file" name="image" id="image" class="form-control" />
                                </div>
                                <span asp-validation-for="ImageURL" class="text-danger"></span>
                            </div>
            <div class="form-group">
                <label asp-for="StartDate" class="control-label"></label>
                <input asp-for="StartDate" class="form-control" />
                <span asp-validation-for="StartDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="EndDate" class="control-label"></label>
                <input asp-for="EndDate" class="form-control" />
                <span asp-validation-for="EndDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="MovieCategory" class="control-label"></label>
                <select asp-for="MovieCategory" class="form-control" asp-items="ViewBag.Categories"></select>
                <span asp-validation-for="MovieCategory" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CinemaId" class="control-label"></label>
                <select asp-for="CinemaId" class="form-control" asp-items="ViewBag.Cinemas"></select>
                <span asp-validation-for="CinemaId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ProducerId" class="control-label"></label>
                <select asp-for="ProducerId" class="form-control" asp-items="ViewBag.Producers"></select>
                <span asp-validation-for="ProducerId" class="text-danger"></span>
            </div>
             <div class="form-group">
                <label asp-for="ActorIds" class="control-label"></label>
                <select asp-for="ActorIds" class="form-control" asp-items="ViewBag.Actors"></select>
                <span asp-validation-for="ActorIds" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}