Group 1/Group 1/Group 1/MvcProject2/MvcProject2/Models/Order.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace MvcProject2.Models
{
    public class Order
    {
        [Key]
        public int Id { get; set; }

        public string Email { get; set; }

        public string UserId { get; set; }
        [ForeignKey(nameof(UserId))]
        public ApplicationUser User { get; set; }

        public List<OrderItem> OrderItems { get; set; }
    }
}

Group 1/Group 1/Group 1/MvcProject2/MvcProject2/ViewModels/ShoppingCart.cs
using MvcProject2.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.DependencyInjection;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MvcProject2.ViewModels
{
    public class ShoppingCart
    {
        public AppDbContext _context { get; set; }

        public string ShoppingCartId { get; set; }
        public List<ShoppingCartItem> ShoppingCartItems { get; set; }

        public ShoppingCart(AppDbContext context)
        {
            _context = context;
        }

        public static ShoppingCart GetShoppingCart(IServiceProvider services)
        {
            ISession session = services.GetRequiredService<IHttpContextAccessor>()?.HttpContext.Session;
            var context = services.GetService<AppDbContext>();

            string cartId = session.GetString("CartId") ?? Guid.NewGuid().ToString();
            session.SetString("CartId", cartId);

            return new ShoppingCart(context) { ShoppingCartId = cartId };
        }

        public void AddItemToCart(Movie movie)
        {
            var shoppingCartItem = _context.ShoppingCartItems.FirstOrDefault(n => n.Movie.Id == movie.Id && n.ShoppingCartId == ShoppingCartId);

            if (shoppingCartItem == null)
            {
                shoppingCartItem = new ShoppingCartItem()
                {
                    ShoppingCartId = ShoppingCartId,
                    Movie = movie,
                    Amount = 1
                };

                _context.ShoppingCartItems.Add(shoppingCartItem);
            }
            else
            {
                shoppingCartItem.Amount++;
            }
            _context.SaveChanges();
        }

        public void RemoveItemFromCart(Movie movie)
        {
            var shoppingCartItem = _context.ShoppingCartItems.FirstOrDefault(n => n.Movie.Id == movie.Id && n.ShoppingCartId == ShoppingCartId);

            if (shoppingCartItem != null)
            {
                if (shoppingCartItem.Amount > 1)
                {
                    shoppingCartItem.Amount--;
                }
                else
                {
                    _context.ShoppingCartItems.Remove(shoppingCartItem);
                }
            }
            _context.SaveChanges();
        }

        public List<ShoppingCartItem> GetShoppingCartItems()
        {
            return ShoppingCartItems ?? (ShoppingCartItems = _context.ShoppingCartItems.Where(n => n.ShoppingCartId == ShoppingCartId).Include(n => n.Movie).ToList());
        }

        public double GetShoppingCartTotal() => _context.ShoppingCartItems.Where(n => n.ShoppingCartId == ShoppingCartId).Select(n => n.Movie.Price * n.Amount).Sum();

        public async Task ClearShoppingCartAsync()
        {
            var items = await _context.ShoppingCartItems.Where(n => n.ShoppingCartId == ShoppingCartId).ToListAsync();
            _context.ShoppingCartItems.RemoveRange(items);
            await _context.SaveChangesAsync();
        }
    }
}

Group 1/Group 1/Group 1/MvcProject2/MvcProject2/Controllers/MoviesController.cs
using MvcProject2.ViewModels;
using MvcProject2.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using MvcProject2.Repository;

namespace MvcProject2.Controllers
{
    [Authorize(Roles = UserRoles.Admin)]
    public class MoviesController : Controller
    {
        IMovieRepository moviesRepository;

        public MoviesController(IMovieRepository _movieRepo)
        {
            moviesRepository = _movieRepo;
        }

        [AllowAnonymous]
        public IActionResult Index()
        {
            var allMovies = moviesRepository.GetAllAsync();
            return View(allMovies);
        }

        [AllowAnonymous]
        public IActionResult Filter(string searchString)
        {
            var allMovies = moviesRepository.GetAllAsync();

            if (!string.IsNullOrEmpty(searchString))
            {
                var filteredResultNew = allMovies.Where(n => string.Equals(n.Name, searchString, System.StringComparison.CurrentCultureIgnoreCase) || string.Equals(n.Description, searchString, System.StringComparison.CurrentCultureIgnoreCase)).ToList();

                return View("Index", filteredResultNew);
            }

            return View("Index", allMovies);
        }

        [AllowAnonymous]
        public async Task<IActionResult> Details(int id)
        {
            var movieDetail = await moviesRepository.GetMovieById(id);
       
            return View(movieDetail);
        }

        public IActionResult Create()
        {
            var movieDropdownsData = moviesRepository.GetNewMovieDropdownsValues();

            ViewBag.Cinemas = new SelectList(movieDropdownsData.Cinemas, "Id", "Name");
            ViewBag.Producers = new SelectList(movieDropdownsData.Producers, "Id", "FullName");
            ViewBag.Actors = new SelectList(movieDropdownsData.Actors, "Id", "FullName");
            var enumData = from MovieCategory e in Enum.GetValues(typeof(MovieCategory))
                           select new
                           {
                               Id = (int)e,
                               FullName = e.ToString()
                           };
            ViewBag.Categories = new SelectList(enumData, "Id", "FullName");

            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(NewMovieVM movie, IFormFile image)
        {
            movie.ImageURL = "/Images/pexels - alex - azabache - 3879071.jpg";
            if (movie.Name != null && movie.Description != null && movie.Price != null
                 && movie.StartDate != null && movie.EndDate != null && movie.MovieCategory != null
                 && movie.ActorIds != null && movie.ActorIds.Count > 0 && movie.CinemaId != null
                 && movie.ProducerId != null)
            {
                if (image != null && image.Length > 0)
                {
                    var fileName = Path.GetFileName(image.FileName);
                    var filePath = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot\\Images\\", fileName);

                    using (var fileStream = new FileStream(filePath, FileMode.Create))
                    {
                        image.CopyTo(fileStream);
                    }

                    movie.ImageURL = "/Images/" + fileName;
                }

               await moviesRepository.AddNewMovieAsync(movie);
                return RedirectToAction("Index");
            }
            else
            {
                var movieDropdownsData = moviesRepository.GetNewMovieDropdownsValues();

                ViewBag.Cinemas = new SelectList(movieDropdownsData.Cinemas, "Id", "Name");
                ViewBag.Producers = new SelectList(movieDropdownsData.Producers, "Id", "FullName");
                ViewBag.Actors = new SelectList(movieDropdownsData.Actors, "Id", "FullName");
                var enumData = from MovieCategory e in Enum.GetValues(typeof(MovieCategory))
                               select new
                               {
                                   Id = (int)e,
                                   FullName = e.ToString()
                               };
                ViewBag.Categories = new SelectList(enumData, "Id", "FullName");

                return View(movie);
            }
        }


        public async Task<ActionResult> Edit(int id)
        {
            var movieDetails = await moviesRepository.GetMovieById(id);
            if (movieDetails == null) return View("NotFound");

            var response = new NewMovieVM()
            {
                Id = movieDetails.Id,
                Name = movieDetails.Name,
                Description = movieDetails.Description,
                Price = movieDetails.Price,
                StartDate = movieDetails.StartDate,
                EndDate = movieDetails.EndDate,
                ImageURL = movieDetails.ImageURL,
                MovieCategory = movieDetails.MovieCategory,
                CinemaId = movieDetails.CinemaId,
                ProducerId = (int)movieDetails.ProducerId,
                ActorIds = movieDetails.Actors_Movies.Select(n => n.ActorId).ToList(),
            };

            var movieDropdownsData = moviesRepository.GetNewMovieDropdownsValues();
            ViewBag.Cinemas = new SelectList(movieDropdownsData.Cinemas, "Id", "Name");
            ViewBag.Producers = new SelectList(movieDropdownsData.Producers, "Id", "FullName");
            ViewBag.Actors = new SelectList(movieDropdownsData.Actors, "Id", "FullName");
            var enumData = from MovieCategory e in Enum.GetValues(typeof(MovieCategory))
                           select new
                           {
                               Id = (int)e,
                               FullName = e.ToString()
                           };
            ViewBag.Categories = new SelectList(enumData, "Id", "FullName");

            return View(response);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, NewMovieVM movie, IFormFile image)
        {
            if (id != movie.Id) return View("NotFound");

            if (movie.Name != null && movie.Description != null && movie.Price != null
                && movie.StartDate != null && movie.EndDate != null && movie.MovieCategory != null
                && movie.ActorIds != null && movie.ActorIds.Count > 0 && movie.CinemaId != null
                && movie.ProducerId != null)
            {

                if (image != null && image.Length > 0)
                {
                    var fileName = Path.GetFileName(image.FileName);
                    var filePath = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot\\Images\\", fileName);

                    using (var fileStream = new FileStream(filePath, FileMode.Create))
                    {
                        image.CopyTo(fileStream);
                    }

                    movie.ImageURL = "/Images/" + fileName;

                    await moviesRepository.UpdateMovieAsync(movie);

                    return RedirectToAction("Index");
                }
                await moviesRepository.UpdateMovieAsync(movie);

                return RedirectToAction("Index");
                //return View(movie);

            }
            var movieDropdownsData = moviesRepository.GetNewMovieDropdownsValues();

            ViewBag.Cinemas = new SelectList(movieDropdownsData.Cinemas, "Id", "Name");
            ViewBag.Producers = new SelectList(movieDropdownsData.Producers, "Id", "FullName");
            ViewBag.Actors = new SelectList(movieDropdownsData.Actors, "Id", "FullName");
            var enumData = from MovieCategory e in Enum.GetValues(typeof(MovieCategory))
                           select new
                           {
                               Id = (int)e,
                               FullName = e.ToString()
                           };
            ViewBag.Categories = new SelectList(enumData, "Id", "FullName");

            return View(movie);


        }
        public IActionResult Delete(int id)
        {
            moviesRepository.DeleteMovie(id);
            return RedirectToAction("Index");
        }

    }
}

Group 1/Group 1/Group 1/MvcProject2/MvcProject2/Controllers/OrdersController.cs
using MvcProject2.Repository;
using MvcProject2.ViewModels;
using MvcProject2.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;



namespace MvcProject2.Controllers
{
    [Authorize] 
    public class OrdersController : Controller
    {

        private readonly IMovieRepository _moviesRepo;
        //private readonly IMoviesService _moviesRepo;
        private readonly ShoppingCart _shoppingCart;
        private readonly IOrderRepository _ordersService;
        //  IMovieRepository  IMoviesService
        public OrdersController(IMovieRepository moviesService, ShoppingCart shoppingCart, IOrderRepository ordersService)
        {
            _moviesRepo = moviesService;
            _shoppingCart = shoppingCart;
            _ordersService = ordersService;
        }

        public async Task<IActionResult> Index()
        {
            string userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            string userRole = User.FindFirstValue(ClaimTypes.Role);

            var orders = await _ordersService.GetOrdersByUserIdAndRoleAsync(userId, userRole);
            return View(orders);
        }

        public IActionResult ShoppingCart()
        {
            var items = _shoppingCart.GetShoppingCartItems();
            _shoppingCart.ShoppingCartItems = items;

            var response = new ShoppingCartVM()
            {
                ShoppingCart = _shoppingCart,
                ShoppingCartTotal = _shoppingCart.GetShoppingCartTotal()
            };

            return View(response);
        }

        public async Task<IActionResult> AddItemToShoppingCart(int id)
        {
            var item = await _moviesRepo.GetMovieById(id);

            if (item != null)
            {
                _shoppingCart.AddItemToCart(item);
            }
            return RedirectToAction(nameof(ShoppingCart));
        }

        public async Task<IActionResult> RemoveItemFromShoppingCart(int id)
        {
            var item = await _moviesRepo.GetMovieById(id);

            if (item != null)
            {
                _shoppingCart.RemoveItemFromCart(item);
            }
            return RedirectToAction(nameof(ShoppingCart));
        }

        public async Task<IActionResult> CompleteOrder()
        {
            var items = _shoppingCart.GetShoppingCartItems();
            string userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            string userEmailAddress = User.FindFirstValue(ClaimTypes.Email);

            await _ordersService.StoreOrderAsync(items, userId, userEmailAddress);
            await _shoppingCart.ClearShoppingCartAsync();

            return View("OrderCompleted");
        }
    }
}

Group 1/Group 1/Group 1/MvcProject2/MvcProject2/Views/Orders/Index.cshtml
@using MvcProject2.Models;
@model List<Order>

@{ 
    ViewData["Title"] = "All orders";
}
<head>
    <link rel="stylesheet"
          href="https://fonts.googleapis.com/css?family=Montserrat:wght@100;400;800&display=swap">
</head>
<style>
    body {
        background: url('../Images/body-bg.gif');
        background: black;
        color: white;
    }
</style>
<div class="row">
    <div class="col-md-8 offset-2">
        <p>
            <h4>List of all your orders</h4>
        </p>

        <table class="table table-dark table-hover">
            <thead>
                <tr>
                    <th>Order ID</th>
                    <th>Items</th>
                    <th>Total</th>
                    @if (User.Identity.IsAuthenticated && User.IsInRole("Admin"))
                    {
                        <th>User</th>
                    }
                </tr>
            </thead>
            <tbody>
                @foreach (var order in Model)
                {
                <tr>
                    <td class="align-middle">@order.Id</td>
                    <td class="align-middle">
                        <ul style="list-style-type:none">
                            @foreach (var item in order.OrderItems)
                            {
                                <li>
                                    <div class="alert alert-info" role="alert">
                                        <span class="badge bg-success">@item.Amount</span> [@item.Price.ToString("c")] - @item.Movie.Name
                                    </div>
                                </li>
                            }
                        </ul>
                    </td>
                    <td class="align-middle">
                        @order.OrderItems.Select(m => m.Movie.Price * m.Amount).Sum().ToString("c")
                    </td>
                    @if (User.Identity.IsAuthenticated && User.IsInRole("Admin"))
                    {
                        <td class="align-middle"> @order.User.FullName </td>
                    }
                    </tr>
                }
            </tbody>
        </table>

    </div>
</div>

Group 1/Group 1/Group 1/MvcProject2/MvcProject2/Views/Orders/OrderCompleted.cshtml
<head>
    <link rel="stylesheet"
          href="https://fonts.googleapis.com/css?family=Montserrat:wght@100;400;800&display=swap">
</head>
<style>
    body {
        background: url('../Images/body-bg.gif');
        background: black;
        color: white;
    }
</style>
<div class="row">
    <div class="col-md-6 offset-3 alert alert-success text-center">
        <h2>Order completed successfully</h2>
        <p>You can check all your orders in the Orders section of your profile</p>
        <hr />
        <p>Thank you!</p>
    </div>
</div>

Group 1/Group 1/Group 1/MvcProject2/MvcProject2/Views/Orders/ShoppingCart.cshtml
@using MvcProject2.ViewModels;
@model ShoppingCartVM

@{
    ViewData["Title"] = "Shopping cart summary";
}
<head>
    <link rel="stylesheet"
          href="https://fonts.googleapis.com/css?family=Montserrat:wght@100;400;800&display=swap">
</head>
<style>
    body {
        background: url('../Images/body-bg.gif');
        background: black;
        color: white;
    }
</style>
<div class="row">
    <div class="col-md-8 offset-2">
        <div class="text-center">
            <h2>Your shopping cart summary</h2>
        </div>

        <table class="table table-dark table-hover">
            <thead>
                <tr>
                    <th>Selected amount</th>
                    <th>Movie</th>
                    <th>Price</th>
                    <th>Subtotal</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model.ShoppingCart.ShoppingCartItems)
                {
                    <tr>
                        <td class="align-middle">@item.Amount</td>
                        <td class="align-middle">@item.Movie.Name</td>
                        <td class="align-middle">@item.Movie.Price.ToString("c")</td>
                        <td class="align-middle">@((item.Amount*item.Movie.Price).ToString("c"))</td>
                        <td class="align-middle">
                            <a class="text-danger" asp-controller="Orders" asp-action="RemoveItemFromShoppingCart"
                               asp-route-id="@item.Movie.Id">
                                <i class="bi bi-cart-dash"></i>
                            </a>
                            |
                            <a class="text-success" asp-controller="Orders" asp-action="AddItemToShoppingCart"
                               asp-route-id="@item.Movie.Id">
                                <i class="bi bi-cart-plus"></i>
                            </a>
                        </td>
                    </tr>
                }
            </tbody>
            <tfoot>
                <tr>
                    <td colspan="2"></td>
                    <td><b>Total:</b></td>
                    <td>
                        @Model.ShoppingCartTotal.ToString("c")
                    </td>
                    <td></td>
                </tr>
            </tfoot>
        </table>

        <div class="text-right">
            <div class="btn-group">
                <a class="btn btn-outline-success " asp-controller="Orders" asp-action="CompleteOrder">
                        Complete Orders
                    </a>
                <div id="paypal-btn"></div>
                <span style="padding:5px"></span>

                <a class="btn btn-outline-success padding-right" asp-controller="Movies" asp-action="Index">
                    Add more items
                </a>
            </div>
        </div>

    </div>
</div>